stages:
  - build

#################### BUILD STAGE ####################
.docker_build_template: &docker_build_template
  stage: build
  tags:
    - builder
  dependencies: []

build_ui_image:
  <<: *docker_build_template
  script:
    - docker build --rm --build-arg build_tag=$CI_COMMIT_SHA -t gcr.io/mist-ops/ui:$CI_COMMIT_SHA .
    - docker tag gcr.io/mist-ops/ui:$CI_COMMIT_SHA gcr.io/mist-ops/ui:$CI_COMMIT_REF_SLUG
    - docker tag gcr.io/mist-ops/ui:$CI_COMMIT_SHA mist/ui:$CI_COMMIT_SHA
    - docker tag gcr.io/mist-ops/ui:$CI_COMMIT_REF_SLUG mist/ui:$CI_COMMIT_REF_SLUG
    - docker push gcr.io/mist-ops/ui:$CI_COMMIT_SHA
    - docker push gcr.io/mist-ops/ui:$CI_COMMIT_REF_SLUG
    - docker push mist/ui:$CI_COMMIT_SHA
    - docker push mist/ui:$CI_COMMIT_REF_SLUG
